import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import Navbar from "@/components/navbar";
import { AuthProvider } from "@/context/auth-context";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthProvider>
            <header className="sticky z-50 top-0">
              <Navbar />
            </header>
            {children}
            <Toaster
              position="top-right"
              toastOptions={{
                className: "text-sm",
                success: {
                  style: { background: "#16a34a", color: "white" },
                },
                error: {
                  style: { background: "#dc2626", color: "white" },
                },
              }}
            />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
