// import "dotenv/config";
// declare const _default: import("@prisma/config").PrismaConfigInternal;
// export default _default;
// //# sourceMappingURL=prisma.config.d.ts.map

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"]!,
  },
});
